version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
      target: mikro-orm
    env_file: .env
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
  db:
    image: 'postgres:16.2'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=Test
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - pgdata-fehradvice:/var/lib/postgresql/data
volumes:
  pgdata-fehradvice:
